services:
  - type: web
    name: bluesky-transactions
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: APP_KEY
        value: "base64:3+df9HHCop2mges/DjkQSPFUExdnLto1XTa71xQaLiE="
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_NAME
        value: "BLUESKY Transactions"
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: bluesky-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: bluesky-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: bluesky-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: bluesky-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: bluesky-db
          property: password
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: sync

databases:
  - name: bluesky-db
    databaseName: bluesky_transactions
    user: bluesky
